### ISSUE TITLE
Export to Nextflow?

### ISSUE THREAD

**Issue by JulianLegler** [maseiler/swms-monitoring#45]
Actually this should work very well with some minor changes also for nextflow. Should we try it?

**Comment by escapingpanda** [comment]
[failed-nextflow.txt](https://github.com/maseiler/swms-monitoring/files/9577685/failed-nextflow.txt)

[nextflow-writeup.txt](https://github.com/maseiler/swms-monitoring/files/9577704/nextflow-writeup.txt)
